---
version: 0.1.2
files:
  README.md:
  - straw-ios-service-http.js v%.%.%
  - doc/v%.%.%
  ".jsduck.release.json":
  - straw-ios-service-http.js v%.%.%
  - doc/v%.%.%
  bower.json:
  - '"version": "%.%.%",'
